### PR TITLE
Add file-multithreaded execution

### PR DESCRIPTION
**Pull request by tellowkrinkle**
Appears to run without issue when tested with PNGs and JPEGs with Thread Sanitizer enabled
Helps with #53 
Use `--mt-file` or `--mt-file=i` to enable

### CODE REVIEW

**Comment by fhanau** [comment]
Thank you. I actually also implemented file-based multithreading some time ago, but did not clean it up and merge it. I'll look at your changes and will probably merge them as they look more elegant than my approach.

**Comment by andrews05** [comment]
Does this also work when creating/recompressing zip archives?

**Comment by tellowkrinkle** [comment]
It looks like zip file compression is handled separately and I didn't modify it, so it won't work for zip archives

**Comment by fhanau** [comment]
Thanks, this approach turned out to be more elegant than the file-based multithreading I was working on.

**Pull request merged**
